dist: trusty
addons:
  sonarqube:
    token:
      secure:  "oQBGgP+3xZGlmuF9TLKa3csAN/EmbH70iZiHP5lCoYfS4LA1wf50yq6fD2P9vMDhY3ez2r+UmG7+BvMgmyl2Jl0+/3X+G7vSKVK93x7Pk9Sg04qxgWnovw2oewU3Vih+r/EndBbfaGS5JlYjQsy+gNHekUSpCLtDYXncsreYlBuV1Md+9OOUqUUKvaT3k5eTTzoolo14iCQ8Cc8i3kf38MbxlmayCJnl4PVQqFqEsLQDTNHx3h1o4a18eABTS2ZtjyWqn7hdz36buadL6o/2tFgapDv6T50bgojC6HhCQDFDTkvBrvxjh8/hQfUosbeafEU4yWYotA92KZCd63HA0QzlUM8en52l2GtldbkJ7o32EdzMvIm/JPaeFAA1dRF7cBwptWGMy95FSapy8eAxOTVtrTrT5Qq9kRFR4/OD5u3OehJag2BSSVrtERF7WknhNEXTiMlDY4HfdLvYcWT72MXsh8A3s2m7CSt5LSrLZys0etX8BuKiBboS7QIUHeGvu0BxOA7qgZxdr9np5NKDRm7ZZFAbDAnh94KNUyRbLddtJhlIfas2Sjyzf6MLGAe1vGdOG7Y3Qv+D86ZQI/TW7cqMW7jpUXrITDAhGF7LBo2GHWaXHWze3eas9UUU/dBJWlZSJ4SOEN4MZH1Qh01FNMoFBwUiSNk5spZgQKb79nY="
sudo: required
cache:
  directories:
  - $HOME/.sonar
language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
after_success:
  - 'if [ "$PERLBREW_PERL" == "5.26" ] ; then JAVA_HOME=$JAVA_HOME scripts/sonar-report.sh ; fi'
